CREATE TABLE IF NOT EXISTS certificate_of_good_moral (
  certificate_of_good_moral_id INT AUTO_INCREMENT PRIMARY KEY,
  resident_id INT,
  full_name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  civil_status VARCHAR(50),
  date_issued DATE NOT NULL,
  date_expired DATE NOT NULL,
  remarks TEXT,
  request_reason VARCHAR(255),
  transaction_number VARCHAR(50) UNIQUE,
  control_no VARCHAR(50),
  prepared_by_name VARCHAR(255),
  prepared_by_position VARCHAR(255),
  use_signature BOOLEAN DEFAULT FALSE,
  signature_id INT,
  is_active BOOLEAN DEFAULT TRUE,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (resident_id) REFERENCES residents(resident_id),
  FOREIGN KEY (signature_id) REFERENCES official_signature(signature_id),
  INDEX idx_resident_id (resident_id),
  INDEX idx_transaction_number (transaction_number),
  INDEX idx_control_no (control_no),
  INDEX idx_is_active (is_active),
  INDEX idx_date_created (date_created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
