-- Create Certificate of Low Income table
CREATE TABLE IF NOT EXISTS `certificate_of_low_income` (
  `certificate_of_low_income_id` INT AUTO_INCREMENT PRIMARY KEY,
  `resident_id` INT,
  `full_name` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `source_of_income` VARCHAR(255),
  `income_amount` VARCHAR(100),
  `civil_status` VARCHAR(50),
  `date_issued` DATE NOT NULL,
  `date_expired` DATE,
  `remarks` TEXT,
  `request_reason` TEXT,
  `transaction_number` VARCHAR(50) UNIQUE,
  `control_no` VARCHAR(50),
  `prepared_by_name` VARCHAR(255),
  `prepared_by_position` VARCHAR(255),
  `use_signature` TINYINT(1) DEFAULT 0,
  `signature_id` INT,
  `is_active` TINYINT(1) DEFAULT 1,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (resident_id) REFERENCES residents(resident_id),
  FOREIGN KEY (signature_id) REFERENCES official_signature(signature_id),
  INDEX idx_resident_id (resident_id),
  INDEX idx_transaction_number (transaction_number),
  INDEX idx_control_no (control_no),
  INDEX idx_is_active (is_active),
  INDEX idx_date_created (date_created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
